version: '3.8'

services:
  web:
    build: .
    container_name: php-router-app
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html    # mount source code agar hot reload
      - ./uploads:/var/www/html/uploads   # <-- mount folder uploads
      - ./_other/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: php-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dummy_DB
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"

volumes:
  db_data:
